<?php
/*El primer hook, utilizamos el hook_help*/
function modu_help($path, $arg){
	switch ($path){
		case "admin/help#modu":
			return "<h1>Esta es la página de ayuda de mi módulo</h1>";
		break;
	}
}
/*Declara la existencia del bloque a drupal*/
function modu_block_info(){
	$blocks['modu'] = array(
		'info' => t('Noticia del dia'),
		'cache' => DRUPAL_CACHE_PER_ROLE,
	);
	return $blocks;
}
/*Una funcion personalizada, para realizar un query*/
function modu_retContent(){
	  //Obtiene la fecha
	  $hoy = getdate();
	  //Calcula la fecha de hace una semana.
	  $fecha_inicio = time();
	  //Calcula el ahora.
	  $fecha_fin = time();
	  //Utilizamos el API para obtener los posts
	  $query = db_select('node', 'n')
	    ->fields('n', array('nid', 'title', 'created'))
	    ->condition('status', 1) //Solo los publicados
	    ->condition('created', array($fecha_inicio, $fecha_fin), 'BETWEEN')
	    ->orderBy('created', 'DESC') //Mas recientes primero
	    ->execute();
	  return $query;
}
/*Csontruye el bloque utilizando el query de la función anterior*/
function modu_block_view($delta = ''){
	switch ($delta){
		case 'modu':
			$block['subject'] = t('Bloque Custom'); //La función t() permite hacer traducible la cadena
			
			if (user_access('access content')){
					$resultado = modu_retContent();
					$items = array();
					foreach ($resultado as $node){
						$items[] = array(
							'data' => l($node->title, 'node/' . $node->nid));
					}
					if (empty($items)){
						$block['content'] = 'No content Avaliable';
					} else {
						$block['content'] = theme('item_list', array('items' => $items));
					
					}
			return $block;
			break;
	}
}
}